import type { Category } from './types';

export const guideCategories: Category[] = [
  { slug: 'coding', label: 'Coding', icon: 'coding' },
  { slug: 'marketing', label: 'Marketing', icon: 'marketing' },
  { slug: 'content-creator', label: 'Content Creator', icon: 'content-creator' },
  { slug: 'educator', label: 'Educator', icon: 'educator' },
  { slug: 'sales', label: 'Sales', icon: 'sales' },
  { slug: 'design', label: 'Design', icon: 'design' },
  { slug: 'data-analysis', label: 'Data Analysis', icon: 'data-analysis' },
  { slug: 'project-management', label: 'Project Management', icon: 'project-management' },
  { slug: 'consulting', label: 'Consulting', icon: 'consulting' },
  { slug: 'finance', label: 'Finance', icon: 'finance' },
  { slug: 'government', label: 'Government', icon: 'government' },
  { slug: 'healthcare', label: 'Healthcare', icon: 'healthcare' },
  { slug: 'legal', label: 'Legal', icon: 'legal' },
  { slug: 'recruiting-hr', label: 'Recruiting HR', icon: 'recruiting-hr' },
  { slug: 'student', label: 'Student', icon: 'student' },
  { slug: 'general', label: 'General', icon: 'general' },
  { slug: 'business-operations', label: 'Business Operations', icon: 'business-operations' },
];

export const toolCategories: Category[] = [
  { slug: 'agents', label: 'Agents', icon: 'agents' },
  { slug: 'consumer', label: 'Consumer', icon: 'consumer' },
  { slug: 'miscellaneous', label: 'Miscellaneous', icon: 'miscellaneous' },
  { slug: 'science', label: 'Science', icon: 'science' },
  { slug: 'coding', label: 'Coding', icon: 'coding' },
  { slug: 'marketing', label: 'Marketing', icon: 'marketing' },
  { slug: 'content-creator', label: 'Content Creator', icon: 'content-creator' },
  { slug: 'educators', label: 'Educators', icon: 'educator' },
  { slug: 'business-operations', label: 'Business Operations', icon: 'business-operations' },
  { slug: 'sales', label: 'Sales', icon: 'sales' },
  { slug: 'finance', label: 'Finance', icon: 'finance' },
  { slug: 'design', label: 'Design', icon: 'design' },
  { slug: 'healthcare', label: 'Healthcare', icon: 'healthcare' },
  { slug: 'consulting', label: 'Consulting', icon: 'consulting' },
  { slug: 'government', label: 'Government', icon: 'government' },
  { slug: 'data-analysis', label: 'Data Analysis', icon: 'data-analysis' },
  { slug: 'project-management', label: 'Project Management', icon: 'project-management' },
  { slug: 'legal', label: 'Legal', icon: 'legal' },
  { slug: 'recruiting-hr', label: 'Recruiting / HR', icon: 'recruiting-hr' },
  { slug: 'students', label: 'Students', icon: 'student' },
];
