import type { Tool } from './types';

export const tools: Tool[] = [
  {
    slug: 'muse-spark-1-3',
    name: 'Muse Spark 1.3',
    description: "Meta's cost-effective, intelligent model",
    categories: ['consumer', 'coding'],
    badgeIcon: 'consumer',
    image: { alt: 'Blue wireframe waves on a dark background' },
  },
  {
    slug: 'claude-fable-5-1',
    name: 'Claude Fable 5.1',
    description: "Anthropic's new flagship, top-rated model",
    categories: ['consumer', 'coding', 'agents'],
    badgeIcon: 'consumer',
    image: { alt: 'Claude Fable 5.1 benchmark table' },
  },
  {
    slug: 'gemini-3-8-flash',
    name: 'Gemini 3.8 Flash',
    description: "Google's strongest Flash model yet for coding and agents",
    categories: ['consumer', 'coding', 'agents'],
    badgeIcon: 'consumer',
    image: { alt: 'Gemini 3.8 Flash announcement visual' },
  },
  {
    slug: 'google-pics',
    name: 'Google Pics',
    description: "Google's Nano Banana image editor built into Docs and Slides",
    categories: ['content-creator', 'design', 'marketing'],
    badgeIcon: 'content-creator',
    image: { alt: 'Collage of colourful posters' },
  },
  {
    slug: 'muse-voice-transcribe',
    name: 'Muse Voice Transcribe',
    description:
      "Muse Voice Transcribe - Meta's live speech-to-text that tracks 20+ speakers and mid-sentence language switches",
    categories: ['miscellaneous', 'business-operations'],
    badgeIcon: 'miscellaneous',
    image: { alt: 'Sound waves on a dark background' },
  },
  {
    slug: 'openclaw-2-0',
    name: 'Openclaw 2.0',
    description: 'Open-source personal agent, rebuilt with easier setup and multiplayer sessions',
    categories: ['agents', 'coding'],
    badgeIcon: 'agents',
    image: { alt: 'Red lobster mascot in front of glowing screens' },
  },
  {
    slug: 'cohere-parse-5',
    name: 'Cohere Parse 5',
    description: 'Low-cost model converting complex documents into machine-readable data',
    categories: ['business-operations', 'data-analysis'],
    badgeIcon: 'business-operations',
    image: { alt: 'Soft blurred light gradient' },
  },
  {
    slug: 'gemini-omni-1-1-flash',
    name: 'Gemini Omni 1.1 Flash',
    description: "Google's video model update with scene extensions and 4K upscaling",
    categories: ['miscellaneous', 'content-creator'],
    badgeIcon: 'miscellaneous',
    image: { alt: 'Gemini Omni 1.1 Flash video stills' },
  },
  {
    slug: 'gemini-3-5-transcribe',
    name: 'Gemini 3.5 Transcribe',
    description: "Google's new speech-to-text model that edits out filler words",
    categories: ['content-creator', 'miscellaneous'],
    badgeIcon: 'content-creator',
    image: { alt: 'Gemini 3.5 Transcribe visual' },
  },
  {
    slug: 'glm-5-3-flash',
    name: 'GLM-5.3-Flash',
    description:
      'Z AI’s new multimodal system revealed as the mystery Ox Alpha model on OpenRouter',
    categories: ['consumer', 'science'],
    badgeIcon: 'consumer',
    image: { alt: 'Line chart comparing model scores' },
  },
  {
    slug: 'h3-max',
    name: 'H3 Max',
    description: "fal's MiniMax H3 remixed video model tuned for speed and quality",
    categories: ['content-creator', 'marketing'],
    badgeIcon: 'content-creator',
    image: { alt: 'Purple pixel-art style model card' },
  },
  {
    slug: 'keenable',
    name: 'Keenable',
    description: 'Search API that lets agents query and learn from the live web',
    categories: ['agents', 'coding'],
    badgeIcon: 'agents',
    image: { alt: 'Keenable website hero' },
  },
];
