import type { IconSvgElement } from '@hugeicons/react';
import {
  AnalyticsUpIcon,
  AppleIcon,
  ArrowRight01Icon,
  BankIcon,
  BriefcaseIcon,
  Cancel01Icon,
  CheckListIcon,
  CoinsIcon,
  CourseIcon,
  DashboardSquare01Icon,
  DatabaseIcon,
  FlaskConicalIcon,
  Grid2X2Icon,
  GridViewIcon,
  InstagramIcon,
  LegalHammerIcon,
  LinkedinIcon,
  MegaphoneIcon,
  Menu01Icon,
  MoreHorizontalIcon,
  MortarboardIcon,
  NewTwitterIcon,
  PaintBrushIcon,
  PenTool01Icon,
  PlayIcon,
  PlaySquareIcon,
  PodcastIcon,
  Presentation01Icon,
  Robot01Icon,
  SentIcon,
  SourceCodeIcon,
  SpotifyIcon,
  StethoscopeIcon,
  StudentIcon,
  UserGroupIcon,
  UserIcon,
  UserSearchIcon,
} from '@hugeicons/core-free-icons';
import type { IconName } from '@/content/types';

/**
 * Seul point d'accès aux icônes Hugeicons. Noms vérifiés sur
 * @hugeicons/core-free-icons 4.3.0. Si un nom manque à l'installation,
 * remplacer ici par le plus proche du même jeu et le noter en commentaire.
 */
export const icons: Record<IconName, IconSvgElement> = {
  menu: Menu01Icon,
  close: Cancel01Icon,
  'arrow-right': ArrowRight01Icon,
  send: SentIcon,
  play: PlayIcon,
  more: MoreHorizontalIcon,
  podcast: PodcastIcon,
  spotify: SpotifyIcon,
  apple: AppleIcon,
  x: NewTwitterIcon,
  instagram: InstagramIcon,
  linkedin: LinkedinIcon,
  all: GridViewIcon,
  coding: SourceCodeIcon,
  marketing: MegaphoneIcon,
  'content-creator': PenTool01Icon,
  educator: MortarboardIcon,
  sales: AnalyticsUpIcon,
  design: PaintBrushIcon,
  'data-analysis': DatabaseIcon,
  'project-management': CheckListIcon,
  consulting: UserGroupIcon,
  finance: CoinsIcon,
  government: BankIcon,
  healthcare: StethoscopeIcon,
  legal: LegalHammerIcon,
  'recruiting-hr': UserSearchIcon,
  student: StudentIcon,
  general: DashboardSquare01Icon,
  'business-operations': BriefcaseIcon,
  agents: Robot01Icon,
  consumer: UserIcon,
  miscellaneous: Grid2X2Icon,
  science: FlaskConicalIcon,
  courses: CourseIcon,
  'daily-guides': PlaySquareIcon,
  workshops: Presentation01Icon,
  community: UserGroupIcon,
};

export function getIcon(name: IconName): IconSvgElement {
  return icons[name];
}
